### ISSUE TITLE
Incorrect div id and placement id

### ISSUE THREAD

**Issue by peterkincses** [Nosto/nosto-react#199]
We are getting incorrect placement ids for campaigns which use the same placements. 

In the NostoRecommendation object, what we see is that instead of getting the div_id (frontpage-carousel-p1) or placement_id (frontpage-carousel-p1), we get the slot_id (frontpage-nosto-5). How can this be corrected? 

We are using version 2.2.2 which seems to be the latest version. Thank you!

![Screenshot 2024-10-30 at 10 35 23](https://github.com/user-attachments/assets/74808563-0b4d-449f-8258-9093cc6a123c)
![Screenshot 2024-10-30 at 10 33 57](https://github.com/user-attachments/assets/c3653f27-e6ec-4422-8d5e-18c09e56db1d)

**Comment by timowestnosto** [comment]
@peterkincses Can you provide a bit more context on what goes wrong here? Maybe a code snippet?

**Comment by peterkincses** [comment]
hi @timowestnosto thank you for your response. Here is the code we use to get NostoRecommendations from our Nosto account:

import { Cart, Customer, NostoProvider, NostoSession } from "@nosto/nosto-react"

```
return (
    <NostoProvider
      account={String(config?.NostoAccountId)}
      recommendationComponent={
        <NostoRecommendations  />
      }
    >
      <>
        {children}
        <NostoSession cart={cart} customer={customer} />
      </>
    </NostoProvider>
  )

export const NostoRecommendations = memo(function NostoRecommendations({
  nostoRecommendation,
}: Props) {
     console.log("NostoRecommendations", NostoRecommendations)
}

```
If you look at the two screenshots attached to the OP, using the "Test - Big Savings on brand favourites" campaign, you can see that in the NostoRecommendations response we get the "slot id" value for "div_id", and also we get the "slot_id" value for "result_id". Without giving too much details, we need to get access to the "placement_id" as the slot ids are different when multiple campaigns use the same placement id. Hope this helps, please let me know if you need more info.

**Comment by Dashue** [comment]
Hi @timowestnosto, thanks for your time.

Going a bit more technical, the implementation of useRenderCampaigns does have access to a lookup of Record<PlacementId, Recommendation> for which it only surfaces the Recommendation to the consumer

Basically the change we're proposing, would be facilitated through the below change or similar if there is one more appropriate.

https://github.com/Nosto/nosto-react/blob/d6abc3816c876ef3a3694499cd96160ad009ae6a/src/hooks/useRenderCampaigns.tsx#L56

 nostoRecommendation={{...recommendation, placementId:key}}

This way when we render a campaign in code, we know what placement id it is from the recommendation object provided and allows us to apply styling on demand from our CMS.

The underlying cause for this issue is that fallback campaigns come through with different result_id and div_id compared to the main campaign, and placement Id is the shared information binding them together that what we require to style all campaigns to the same placement in the same way.

Please let me know if I can elaborate

Thanks again
Johan

**Comment by timowestnosto** [comment]
Closing this now, since the fix is being handled as part of Nosto Support
